package technitium

import (
	"context"
	"crypto/tls"
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"net/url"
	"strings"
	"sync"

	"github.com/xruins/external-dns-technitium-dns/internal/config"
)

// CommentPrefix is the prefix added to every DNS record comment created by this webhook.
// Records without this prefix are treated as externally managed and are never modified or deleted.
const CommentPrefix = "Generated by external-dns-technitium-webhook"

// Client communicates with the Technitium DNS Server REST API.
type Client struct {
	baseURL    string
	username   string
	password   string
	zone       string
	httpClient *http.Client

	tokenMu sync.RWMutex
	token   string
}

// NewClient constructs a Client from the provided configuration.
func NewClient(cfg *config.Config) (*Client, error) {
	transport := &http.Transport{}
	if !cfg.TechnitiumVerifySSL {
		transport.TLSClientConfig = &tls.Config{InsecureSkipVerify: true} //nolint:gosec // intentional opt-in
	}
	return &Client{
		baseURL:  cfg.TechnitiumURL,
		username: cfg.TechnitiumUsername,
		password: cfg.TechnitiumPassword,
		zone:     cfg.Zone,
		httpClient: &http.Client{
			Timeout:   cfg.TechnitiumTimeout,
			Transport: transport,
		},
	}, nil
}

// Login authenticates against Technitium and stores the session token.
func (c *Client) Login(ctx context.Context) error {
	params := url.Values{}
	params.Set("user", c.username)
	params.Set("pass", c.password)
	params.Set("includeInfo", "false")

	var loginResp loginResponse
	if err := c.doGet(ctx, "/api/user/login", params, &loginResp); err != nil {
		return fmt.Errorf("login: %w", err)
	}

	c.tokenMu.Lock()
	c.token = loginResp.Token
	c.tokenMu.Unlock()

	slog.Info("Successfully authenticated with Technitium DNS")
	return nil
}

// getToken returns the current session token.
func (c *Client) getToken() string {
	c.tokenMu.RLock()
	defer c.tokenMu.RUnlock()
	return c.token
}

// doGet performs a GET request against the Technitium API and unmarshals the inner response.
// If the server returns "invalid-token", Login is called once and the request is retried.
func (c *Client) doGet(ctx context.Context, path string, params url.Values, dest interface{}) error {
	return c.doGetWithRetry(ctx, path, params, dest, true)
}

func (c *Client) doGetWithRetry(ctx context.Context, path string, params url.Values, dest interface{}, retry bool) error {
	params.Set("token", c.getToken())

	apiURL := c.baseURL + path + "?" + params.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, apiURL, nil)
	if err != nil {
		return fmt.Errorf("building request: %w", err)
	}

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("executing request: %w", err)
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("reading response body: %w", err)
	}

	var envelope apiResponse
	if err := json.Unmarshal(body, &envelope); err != nil {
		return fmt.Errorf("decoding API envelope: %w", err)
	}

	// Re-authenticate and retry once on expired token.
	if envelope.Status == "invalid-token" && retry {
		slog.Warn("Technitium token expired, re-authenticating")
		if err := c.Login(ctx); err != nil {
			return fmt.Errorf("re-login after token expiry: %w", err)
		}
		// Update params with new token for retry.
		params.Set("token", c.getToken())
		return c.doGetWithRetry(ctx, path, params, dest, false)
	}

	if envelope.Status != "ok" {
		return fmt.Errorf("Technitium API error: %s", envelope.ErrorMessage)
	}

	if dest == nil {
		return nil
	}
	data := envelope.Response
	if len(data) == 0 {
		data = body
	}

	if err := json.Unmarshal(data, dest); err != nil {
		return fmt.Errorf("decoding response body: %w", err)
	}
	return nil
}

// GetAllRecords retrieves every record in the configured zone.
func (c *Client) GetAllRecords(ctx context.Context) ([]Record, error) {
	params := url.Values{}
	params.Set("domain", c.zone)
	params.Set("zone", c.zone)
	params.Set("listZone", "true")

	var resp getRecordsResponse
	if err := c.doGet(ctx, "/api/zones/records/get", params, &resp); err != nil {
		return nil, fmt.Errorf("getting records for zone %q: %w", c.zone, err)
	}
	return resp.Records, nil
}

// GetRecords retrieves records for a specific domain name, optionally filtered by type.
func (c *Client) GetRecords(ctx context.Context, domain, recordType string) ([]Record, error) {
	params := url.Values{}
	params.Set("domain", domain)
	params.Set("zone", c.zone)

	var resp getRecordsResponse
	if err := c.doGet(ctx, "/api/zones/records/get", params, &resp); err != nil {
		return nil, fmt.Errorf("getting records for %q: %w", domain, err)
	}

	if recordType == "" {
		return resp.Records, nil
	}

	var filtered []Record
	for _, r := range resp.Records {
		if strings.EqualFold(r.Type, recordType) {
			filtered = append(filtered, r)
		}
	}
	return filtered, nil
}

// AddRecord creates a DNS record in Technitium.
// If overwrite is true, any existing record with the same name, type, and data is replaced.
func (c *Client) AddRecord(ctx context.Context, domain, recordType, target string, ttl int64, comment string, overwrite bool) error {
	params := url.Values{}
	params.Set("domain", domain)
	params.Set("zone", c.zone)
	params.Set("type", recordType)
	if ttl > 0 {
		params.Set("ttl", fmt.Sprintf("%d", ttl))
	}
	params.Set("comments", comment)
	if overwrite {
		params.Set("overwrite", "true")
	}

	if err := setRecordTypeParams(params, recordType, target); err != nil {
		return err
	}

	if err := c.doGet(ctx, "/api/zones/records/add", params, nil); err != nil {
		return fmt.Errorf("adding %s record %q -> %q: %w", recordType, domain, target, err)
	}
	return nil
}

// DeleteRecord removes a specific DNS record from Technitium.
func (c *Client) DeleteRecord(ctx context.Context, domain, recordType, target string) error {
	params := url.Values{}
	params.Set("domain", domain)
	params.Set("zone", c.zone)
	params.Set("type", recordType)

	if err := setRecordTypeParams(params, recordType, target); err != nil {
		return err
	}

	if err := c.doGet(ctx, "/api/zones/records/delete", params, nil); err != nil {
		return fmt.Errorf("deleting %s record %q -> %q: %w", recordType, domain, target, err)
	}
	return nil
}

// ExtractTarget parses the rData JSON of a record and returns the target string for that type.
func ExtractTarget(recordType string, rData json.RawMessage) (string, error) {
	switch strings.ToUpper(recordType) {
	case "A", "AAAA":
		var d rDataA
		if err := json.Unmarshal(rData, &d); err != nil {
			return "", err
		}
		return d.IPAddress, nil
	case "CNAME":
		var d rDataCNAME
		if err := json.Unmarshal(rData, &d); err != nil {
			return "", err
		}
		return d.CName, nil
	case "TXT":
		var d rDataTXT
		if err := json.Unmarshal(rData, &d); err != nil {
			return "", err
		}
		return d.Text, nil
	case "MX":
		var d rDataMX
		if err := json.Unmarshal(rData, &d); err != nil {
			return "", err
		}
		return fmt.Sprintf("%d %s", d.Preference, d.Exchange), nil
	case "NS":
		var d rDataNS
		if err := json.Unmarshal(rData, &d); err != nil {
			return "", err
		}
		return d.NameServer, nil
	case "SRV":
		var d rDataSRV
		if err := json.Unmarshal(rData, &d); err != nil {
			return "", err
		}
		return fmt.Sprintf("%d %d %d %s", d.Priority, d.Weight, d.Port, d.Target), nil
	case "CAA":
		var d rDataCAA
		if err := json.Unmarshal(rData, &d); err != nil {
			return "", err
		}
		return fmt.Sprintf("%d %s %s", d.Flags, d.Tag, d.Value), nil
	case "ANAME":
		var d rDataANAME
		if err := json.Unmarshal(rData, &d); err != nil {
			return "", err
		}
		return d.AName, nil
	default:
		return "", fmt.Errorf("unsupported record type: %s", recordType)
	}
}

// setRecordTypeParams populates the URL parameters required for a given record type and target value.
func setRecordTypeParams(params url.Values, recordType, target string) error {
	switch strings.ToUpper(recordType) {
	case "A", "AAAA":
		params.Set("ipAddress", target)
	case "CNAME":
		params.Set("cname", target)
	case "TXT":
		params.Set("text", target)
	case "MX":
		// target format: "<preference> <exchange>", e.g. "10 mail.example.com"
		parts := strings.SplitN(target, " ", 2)
		if len(parts) != 2 {
			return fmt.Errorf("invalid MX target %q: expected \"<preference> <exchange>\"", target)
		}
		params.Set("preference", parts[0])
		params.Set("exchange", parts[1])
	case "NS":
		params.Set("nameServer", target)
	case "SRV":
		// target format: "<priority> <weight> <port> <target>", e.g. "10 20 80 srv.example.com"
		parts := strings.SplitN(target, " ", 4)
		if len(parts) != 4 {
			return fmt.Errorf("invalid SRV target %q: expected \"<priority> <weight> <port> <target>\"", target)
		}
		params.Set("priority", parts[0])
		params.Set("weight", parts[1])
		params.Set("port", parts[2])
		params.Set("target", parts[3])
	case "CAA":
		// target format: "<flags> <tag> <value>", e.g. "0 issue \"letsencrypt.org\""
		parts := strings.SplitN(target, " ", 3)
		if len(parts) != 3 {
			return fmt.Errorf("invalid CAA target %q: expected \"<flags> <tag> <value>\"", target)
		}
		params.Set("flags", parts[0])
		params.Set("tag", parts[1])
		params.Set("value", parts[2])
	case "ANAME":
		params.Set("aname", target)
	default:
		return fmt.Errorf("unsupported record type: %s", recordType)
	}
	return nil
}
