package webhook

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/xruins/external-dns-technitium-dns/internal/config"
	"github.com/xruins/external-dns-technitium-dns/internal/technitium"
)

// makeTestServer builds a Server wired with the given zone and domain filters.
// The Technitium client is intentionally nil because these tests only cover handlers
// that do not call the Technitium API.
func makeTestServer(zone string, filters []string) *Server {
	cfg := &config.Config{Zone: zone, DomainFilters: filters}
	return NewServer(cfg, nil)
}

func TestHandleNegotiate_defaultsToZone(t *testing.T) {
	srv := makeTestServer("example.com", nil)

	req := httptest.NewRequest(http.MethodGet, "/", nil)
	w := httptest.NewRecorder()
	srv.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d", w.Code)
	}

	var df DomainFilter
	if err := json.NewDecoder(w.Body).Decode(&df); err != nil {
		t.Fatalf("decoding response: %v", err)
	}
	if len(df.Filters) != 1 || df.Filters[0] != "example.com" {
		t.Errorf("unexpected filters: %v", df.Filters)
	}
}

func TestHandleNegotiate_explicitFilters(t *testing.T) {
	srv := makeTestServer("example.com", []string{"a.example.com", "b.example.com"})

	req := httptest.NewRequest(http.MethodGet, "/", nil)
	w := httptest.NewRecorder()
	srv.ServeHTTP(w, req)

	var df DomainFilter
	if err := json.NewDecoder(w.Body).Decode(&df); err != nil {
		t.Fatalf("decoding response: %v", err)
	}
	if len(df.Filters) != 2 {
		t.Errorf("expected 2 filters, got %v", df.Filters)
	}
}

func TestHandleAdjustEndpoints_passThrough(t *testing.T) {
	srv := makeTestServer("example.com", nil)

	body := `[{"dnsName":"www.example.com","targets":["1.2.3.4"],"recordType":"A"}]`
	req := httptest.NewRequest(http.MethodPost, "/adjustendpoints", strings.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()
	srv.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d", w.Code)
	}

	var endpoints []*Endpoint
	if err := json.NewDecoder(w.Body).Decode(&endpoints); err != nil {
		t.Fatalf("decoding response: %v", err)
	}
	if len(endpoints) != 1 || endpoints[0].DNSName != "www.example.com" {
		t.Errorf("unexpected endpoints: %v", endpoints)
	}
}

func TestRecordsToEndpoints_groupsByNameAndType(t *testing.T) {
	records := []technitium.Record{
		makeARecord("www.example.com", "1.2.3.4", 3600),
		makeARecord("www.example.com", "5.6.7.8", 3600),
		makeARecord("api.example.com", "9.10.11.12", 300),
	}

	endpoints := recordsToEndpoints(records)

	if len(endpoints) != 2 {
		t.Fatalf("expected 2 endpoints, got %d", len(endpoints))
	}

	www := findEndpoint(endpoints, "www.example.com")
	if www == nil {
		t.Fatal("www.example.com endpoint not found")
	}
	if len(www.Targets) != 2 {
		t.Errorf("expected 2 targets for www, got %d", len(www.Targets))
	}
}

func TestRecordsToEndpoints_skipsDisabled(t *testing.T) {
	records := []technitium.Record{
		{Name: "disabled.example.com", Type: "A", TTL: 300, Disabled: true,
			RData: json.RawMessage(`{"ipAddress":"1.2.3.4"}`)},
	}
	endpoints := recordsToEndpoints(records)
	if len(endpoints) != 0 {
		t.Errorf("expected 0 endpoints, got %d", len(endpoints))
	}
}

func TestRecordsToEndpoints_skipSOA(t *testing.T) {
	records := []technitium.Record{
		{Name: "example.com", Type: "SOA", TTL: 3600,
			RData: json.RawMessage(`{}`)},
	}
	endpoints := recordsToEndpoints(records)
	if len(endpoints) != 0 {
		t.Errorf("expected 0 endpoints, got %d", len(endpoints))
	}
}

func TestBuildComment_usesResourceLabel(t *testing.T) {
	ep := &Endpoint{
		DNSName: "www.example.com",
		Labels:  map[string]string{"external-dns/resource": "service/default/my-svc"},
	}
	comment := buildComment(ep)
	if !strings.Contains(comment, "service/default/my-svc") {
		t.Errorf("expected resource label in comment, got: %s", comment)
	}
}

func TestBuildComment_fallsBackToDNSName(t *testing.T) {
	ep := &Endpoint{DNSName: "www.example.com"}
	comment := buildComment(ep)
	if !strings.Contains(comment, "www.example.com") {
		t.Errorf("expected dnsName in comment, got: %s", comment)
	}
}

func TestIsOwnedRecord_owned(t *testing.T) {
	r := technitium.Record{Comments: "Generated by external-dns-technitium-webhook (resource: foo)"}
	if !isOwnedRecord(r) {
		t.Error("expected record to be owned")
	}
}

func TestIsOwnedRecord_external(t *testing.T) {
	r := technitium.Record{Comments: "managed by someone else"}
	if isOwnedRecord(r) {
		t.Error("expected record to be external")
	}
}

func TestIsAddressRecord(t *testing.T) {
	for _, tc := range []struct {
		rtype string
		want  bool
	}{
		{"A", true},
		{"AAAA", true},
		{"a", true},
		{"CNAME", false},
		{"TXT", false},
		{"MX", false},
	} {
		if got := isAddressRecord(tc.rtype); got != tc.want {
			t.Errorf("isAddressRecord(%q) = %v, want %v", tc.rtype, got, tc.want)
		}
	}
}

// ---- helpers ----

func makeARecord(name, ip string, ttl int64) technitium.Record {
	return technitium.Record{
		Name:  name,
		Type:  "A",
		TTL:   ttl,
		RData: json.RawMessage(`{"ipAddress":"` + ip + `"}`),
	}
}

func findEndpoint(eps []*Endpoint, name string) *Endpoint {
	for _, ep := range eps {
		if ep.DNSName == name {
			return ep
		}
	}
	return nil
}
